//
//  ArticleListModels.swift
//  NYTPopularArticles
//
//  Created by Sharon Varghese on 05/11/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ArticleList
{
  // MARK: Use cases
  
  enum FetchArticleList
  {
    struct Request
    {
        let numberOfDays: [Int]
    }
    struct Response
    {
        let articles: [Article]?
        let error: ErrorInfo?
    }
    struct ViewModel
    {
        let articles: [Article]?
        let error: ErrorInfo?
    }
  }
}
