//
//  ArticleListRouter.swift
//  NYTPopularArticles
//
//  Created by Sharon Varghese on 05/11/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ArticleListRoutingLogic
{
  func routeToArticleDetail(segue: UIStoryboardSegue?)
}

protocol ArticleListDataPassing
{
  var dataStore: ArticleListDataStore? { get }
}

class ArticleListRouter: NSObject, ArticleListRoutingLogic, ArticleListDataPassing
{
  weak var viewController: ArticleListViewController?
  var dataStore: ArticleListDataStore?
  
  // MARK: Routing
  
  func routeToArticleDetail(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! ArticleDetailViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToArticleDetail(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "ArticleDetailViewControllerID") as! ArticleDetailViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToArticleDetail(source: dataStore!, destination: &destinationDS)
      navigateToArticleDetail(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
  func navigateToArticleDetail(source: ArticleListViewController, destination: ArticleDetailViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToArticleDetail(source: ArticleListDataStore, destination: inout ArticleDetailDataStore)
  {
    destination.article = source.article
  }
}
