//
//  ArticleDetailPresenter.swift
//  NYTPopularArticles
//
//  Created by Sharon Varghese on 05/11/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ArticleDetailPresentationLogic
{
  func presentSelectedArticel(response: ArticleDetail.ArticleItem.Response)
}

class ArticleDetailPresenter: ArticleDetailPresentationLogic
{
  weak var viewController: ArticleDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSelectedArticel(response: ArticleDetail.ArticleItem.Response)
  {
      let viewModel = ArticleDetail.ArticleItem.ViewModel(article: response.article)
    viewController?.displayArticle(viewModel: viewModel)
  }
}
